### ISSUE TITLE
Severe memory leak

### ISSUE THREAD

**Issue by SherLock707** [coffebar/waybar-module-pacman-updates#4]
**Describe the bug**
When waybar-module-pacman-updates is running (either in waybar module or in CLI) the memory consumption keeps rising until system freezes.
Killing the process frees up the memory.
No result is returned in prompt after running waybar-module-pacman-updates.

**To Reproduce**
1. Open terminal
2. Run 'waybar-module-pacman-updates'
3. Check memory usage for 'pacman process'

**Expected behavior**
Returns json for waybar without memory issues.

**Additional context**
I have been using it without issue for past 3 months, issue popup today.

**Extra info:**
Version: waybar-module-pacman-updates-git 0.2.2-1  (AUR)  [AUR pkg](https://aur.archlinux.org/packages/waybar-module-pacman-updates-git)
OS: Arch linux
FS: btrfs
RAM: 16GB DDR5

**Comment by coffebar** [comment]
Hi, can't reproduce on Arch. 
Both **pacman** and **waybar-module-pacman-updates** packages wasn't updated this year. 
It seems something is broke in your pacman data. 
**waybar-module-pacman-updates** uses only this 2 commands to fetch updates:
`checkupdates --nosync --nocolor`
`checkupdates --nocolor`

If these not work, look for a help related to checkupdates and pacman.

Thanks. Sorry for the inconvenience.

**Comment by SherLock707** [comment]
`checkupdates`   worked without issue, so ran `waybar-module-pacman-updates` again! surprise it ran without issue!
Did not do anything, just disabled the waybar module for a while, now its working perfectly!

Thanks for quick response and your work!

**Comment by BluishHumility** [comment]
@SherLock707 have you been having issues syncing to repository mirrors recently? I ask because I have seen a lot of mirror syncing issues in the forums recently, and I am wondering if the two issues could be related.

I personally have had no issues at all with `waybar-module-pacman-updates`; it is practically undetectable from a resource-usage standpoint. But I also have not had any issues syncing with repository mirrors.

I _have_ seen other folks announce `waybar-module-pacman-updates` appears to have a memory leak type of issue sometimes, for example this topic: https://forum.garudalinux.org/t/update-checker-using-massive-amount-of-ram/34594?u=bluishhumility. Some of these folks are also having the mirror syncing issue, which is what got me to thinking.

In the current code, the `thread::spawn` that is used to run the `sync_database` function periodically is not monitored or joined (so the spawned thread will run independently in the background). If the `sync_database` function takes longer to execute than the interval between executions (for example, because it is hung trying to connect to the mirrors), it is possible that multiple instances of the `checkupdates` command could be running concurrently. My theory is these hung processes could start to pile up, eventually leading to the memory issue.

I am not a developer and my understanding of this code is very incomplete, so if I am mistaken or talking out of my hat a bit then I apologize. At some point I did end up talking to a chat bot about the code (the bot definitely has a better grasp on Rust than I do) and for what it's worth it had this suggestion:

> To address this potential issue, you might want to use a synchronization mechanism to ensure that only one instance of sync_database runs at a time. One way to achieve this is by using a simple boolean flag. Here's an example modification to your code:
> ```
> use std::sync::{Arc, Mutex};
> 
> // ...
> 
> const SLEEP_SECONDS: u16 = 5;
> const SLEEP_DURATION: Duration = Duration::from_secs(SLEEP_SECONDS as u64);
> static SYNC_FLAG: Arc<Mutex<bool>> = Arc::new(Mutex::new(false));
> 
> // ...
> 
> fn main() -> Result<(), Error> {
>     let sync_flag = Arc::clone(&SYNC_FLAG);
> 
>     thread::spawn(move || {
>         loop {
>             // Acquire lock, and execute sync_database if the flag is false
>             if let Ok(mut guard) = sync_flag.lock() {
>                 if !*guard {
>                     sync_database();
>                     *guard = true;
>                 }
>             }
> 
>             std::thread::sleep(SLEEP_DURATION);
>         }
>     });
> 
>     let mut iter: u16 = 0;
>     let update_on_iter = 300 / SLEEP_SECONDS;
> 
>     loop {
>         // Main loop checking for updates
> 
>         // Release the lock when the condition is met
>         if iter >= update_on_iter {
>             if let Ok(mut guard) = SYNC_FLAG.lock() {
>                 *guard = false;
>             }
>             iter = 0;
>         }
> 
>         // Rest of the code...
> 
>         iter += 1;
>         std::thread::sleep(SLEEP_DURATION);
>     }
> }
> ```

I am not sure if this is a good suggestion or not, but I thought I would pass it along in case you would be willing to take a look.

Thank you, and thanks also for the great Waybar module! :wave:

**Comment by p134c0d3** [comment]
@SherLock707 I can confirm @BluishHumility's comment as this happened to me today. There was an error retrieving `extra.db` in the sync, and after that happened I noticed my system begin to freeze, memory and CPU consumption rose to 97-99% (Intel i7-11700k CPU, 16GB RAM), and bashtop showed `pacman -Qu --dbpath /tmp/checkup-db-1000/` being the culprit using up to 13.7 GiB of RAM before slowly decreasing in size. This also happens very sporadically, but enough to bring it up.
Version of `waybar-module-pacman-updates-git` being used is 0.2.2-1
Also agree with @BluishHumility that normally it runs great & is a great addition to my Sway desktop! If there's anything else I can help provide just let me know.

**Comment by coffebar** [comment]
Released https://github.com/coffebar/waybar-module-pacman-updates/commit/bee0abfa354bb025da14801cee59936e352e9963
